contact:
    path: /kontakt
    controller: App\Controller\ContactController::index

contact_confirmation:
    path: /kontakt/nachricht-erhalten
    controller: App\Controller\ContactController::confirmation

history:
    path: /die-historie-des-jeep
    controller: App\Controller\StaticContentController::history

homepage:
    path: /
    controller: App\Controller\StaticContentController::homepage

imprint:
    path: /impressum
    controller: App\Controller\LegalContentController::imprint

leasing:
    path: /den-jeep-mieten
    controller: App\Controller\StaticContentController::leasing

privacy:
    path: /datenschutz
    controller: App\Controller\LegalContentController::privacy

vehicle:
    path: /der-jeep-im-detail
    controller: App\Controller\VehicleContentController::index

vehicle_accessories:
    path: /der-jeep-im-detail/das-zubehör
    controller: App\Controller\VehicleContentController::index

vehicle_cb_radio:
    path: /der-jeep-im-detail/das-cb-funkgeraet-mit-antenne
    controller: App\Controller\VehicleContentController::index

vehicle_fog_lights:
    path: /der-jeep-im-detail/die-nebelscheinwerfer
    controller: App\Controller\VehicleContentController::fogLights

vehicle_lightbar:
    path: /der-jeep-im-detail/der-lampenbuegel
    controller: App\Controller\VehicleContentController::index

vehicle_paintjob:
    path: /der-jeep-im-detail/die-lackierung
    controller: App\Controller\VehicleContentController::paintjob

vehicle_panels:
    path: /der-jeep-im-detail/die-verkleidungen
    controller: App\Controller\VehicleContentController::panels

vehicle_rims:
    path: /der-jeep-im-detail/die-felgen-und-reifen
    controller: App\Controller\VehicleContentController::rims

vehicle_seats:
    path: /der-jeep-im-detail/die-sitze-und-teppiche
    controller: App\Controller\VehicleContentController::seats

vehicle_softtop:
    path: /der-jeep-im-detail/das-softtop-mit-halbtueren
    controller: App\Controller\VehicleContentController::softtop

vehicle_winch:
    path: /der-jeep-im-detail/die-seilwinde
    controller: App\Controller\VehicleContentController::index
